spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
#  datasource:
#    embedded-database-connection: h2
application:
  paths:
    path-to-image: "/image.jpg"
  host:
    url: "http://localhost:8080"
  provider:
    url: "http://ipwhois.app/json/"
  short-link-supplier:
    length: 6