spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
#  datasource:
#    embedded-database-connection: h2
application:
  host:
    url: "http://localhost"
  provider:
    url: "http://ipwhois.app/json/"
  short-link-supplier:
    length: 6